# Generated by Django 6.0.3 on 2026-03-29 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_course_enrollment_student_courses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subject',
        ),
    ]
